const $=s=>document.querySelector(s),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const catalog=await fetch('./data/catalog.json').then(r=>r.json());let selected=null,file=null,marker=null,url=null;
const models=await fetch('./data/models.json').then(r=>r.json());
function modelChoices(){const ids=new Set(selected?.occurrences.map(o=>o.modelId)||[]);const choices=models.filter(m=>ids.has(m.id));$('#image-model').innerHTML='<option value="">General image / no specific model</option>'+choices.map(m=>`<option value="${m.id}">${escape(m.name)}</option>`).join('');$('#image-model').disabled=!selected;if(choices.some(m=>m.id===$('#search-model').value))$('#image-model').value=$('#search-model').value;else if(choices.length===1)$('#image-model').value=choices[0].id;}
$('#search-model').innerHTML='<option value="">All models</option>'+models.map(m=>`<option value="${m.id}">${escape(m.name)}</option>`).join('');
function results(){
 const q=$('#structure-search').value.toLowerCase().trim(),modelId=$('#search-model').value;
 const labelQuery=q.replace(/^(?:label\s*|#)/,'').replace(/\s+/g,'');
 const numeric=/^\d+[a-z]?$/.test(labelQuery);
 const matches=(q||modelId)?catalog.structures.filter(s=>s.kind!=='model-note').map(s=>({s,occurrences:s.occurrences.filter(o=>(!modelId||o.modelId===modelId)&&(!q||(!numeric&&[s.name,...s.aliases].some(n=>n.toLowerCase().includes(q)))||String(o.label).toLowerCase().replace(/\s+/g,'')===labelQuery))})).filter(r=>r.occurrences.length).sort((a,b)=>modelId?String(a.occurrences[0].label).localeCompare(String(b.occurrences[0].label),undefined,{numeric:true}):a.s.name.localeCompare(b.s.name)):[];
 $('#structure-choices').innerHTML=matches.slice(0,50).map(({s,occurrences})=>`<button type="button" data-id="${s.id}" aria-pressed="${selected?.id===s.id}"><strong>${escape(s.name)}</strong><br><small>${occurrences.map(o=>escape((models.find(m=>m.id===o.modelId)?.name||o.modelId)+' · Label '+o.label+(o.section?' · '+o.section:''))).join('<br>')}</small></button>`).join('')+(matches.length>50?`<small>Showing 50 of ${matches.length} structures. Search by name or label to narrow the list.</small>`:'')||'<small>'+((q||modelId)?'No matching structures. Try another label or model.':'Choose a model or search by name or label.')+'</small>';
}
$('#search-model').addEventListener('change',()=>{selected=null;modelChoices();$('#selected-structure').textContent='Choose a structure from the results.';results();});
results();
$('#structure-search').addEventListener('input',()=>{selected=null;modelChoices();$('#selected-structure').textContent='Choose a structure from the results.';results();});
$('#structure-choices').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;selected=catalog.structures.find(s=>s.id===b.dataset.id);$('#selected-structure').textContent='Selected: '+selected.name;modelChoices();results();});
function drawMarker(){const old=$('#preview .image-marker');if(old)old.remove();if(marker&&$('#quiz-ready').checked&&!$('#physical-pin').checked){const s=document.createElement('span');s.className='image-marker';s.textContent='A';s.style.left=marker.x*100+'%';s.style.top=marker.y*100+'%';$('#preview .marked-image').append(s);}}
$('#image-file').addEventListener('change',()=>{file=$('#image-file').files[0];marker=null;if(url)URL.revokeObjectURL(url);$('#preview').innerHTML='';if(!file)return;if(file.size>5*1024*1024){$('#message').textContent='Please choose an image smaller than 5 MB.';file=null;return;}url=URL.createObjectURL(file);const wrap=document.createElement('div');wrap.className='marked-image';const img=document.createElement('img');img.src=url;img.alt='Image preview. Click the structure to mark it.';img.addEventListener('click',e=>{if(!$('#quiz-ready').checked||$('#physical-pin').checked)return;const r=img.getBoundingClientRect();marker={x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height};drawMarker();});wrap.append(img);$('#preview').append(wrap);});
$('#quiz-ready').addEventListener('change',()=>{$('#marker-help').hidden=!$('#quiz-ready').checked||$('#physical-pin').checked;drawMarker();});
$('#physical-pin').addEventListener('change',()=>{$('#marker-help').hidden=!$('#quiz-ready').checked||$('#physical-pin').checked;drawMarker();});
const base64=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});
$('#image-form').addEventListener('submit',async e=>{e.preventDefault();const msg=$('#message');if(!selected){msg.textContent='Choose a structure first.';return;}if(!file){msg.textContent='Choose an image first.';return;}const quizReady=$('#quiz-ready').checked;if(quizReady&&!$('#physical-pin').checked&&!marker){msg.textContent='Click the target structure in the image to place marker A.';return;}$('#save-image').disabled=true;msg.textContent='Saving your image…';try{const res=await fetch('./_local/images',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':$('meta[name="local-token"]').content},body:JSON.stringify({structureId:selected.id,modelId:$('#image-model').value,physicalPin:$('#physical-pin').checked,image:{name:file.name,data:await base64(file)},alt:$('#image-alt').value,credit:$('#image-credit').value,quizReady,marker:quizReady&&!$('#physical-pin').checked?marker:null})});const result=await res.json();if(!res.ok)throw Error(result.error||'Could not save the image');msg.textContent=`Saved for ${selected.name}. ${quizReady?'It is ready for mock spotters and image identification.':'It is available in the library.'} You can now add another image.`;}catch(error){msg.textContent=error.message;}finally{$('#save-image').disabled=false;}});
